name: "dewey"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"    
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build: ./api
    container_name: api
    command: ["npm", "run", "dev"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api


volumes:
  postgres_data:
