name: "dewey"

services:
  db:
    image: postgres:latest
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    depends_on:
      - ${DB_HOST}
    build: "./${SERVER_HOST}"
    container_name: ${SERVER_HOST}
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./${SERVER_HOST}:/${SERVER_HOST}"
    entrypoint: ["/bin/sh", "/${SERVER_HOST}/entrypoint.sh"]

  web:
    depends_on:
      - ${DB_HOST}
      - ${SERVER_HOST}
    build: "./${WEB_HOST}"
    container_name: ${WEB_HOST}
    environment:
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      WEB_PORT: ${WEB_PORT}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - "./${WEB_HOST}:/${WEB_HOST}"

volumes:
  postgres_data:
