name: "dewey"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"    
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    depends_on:
      - db
    build: ./server
    container_name: server
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
    entrypoint: ["/bin/sh", "/server/entrypoint.sh"]

volumes:
  postgres_data:
