name: "dewey"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dewey-network

  server:
    depends_on:
      - db
    build: ./server
    container_name: server
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
    networks:
      - dewey-network
    entrypoint: ["/bin/sh", "/server/entrypoint.sh"]

  web:
    depends_on:
      - db
      - server
    build: ./web
    container_name: web
    environment:
      SERVER_URL: ${SERVER_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
    networks:
      - dewey-network

volumes:
  postgres_data:

networks:
  dewey-network:
