services:
  server:
    build: .
    container_name: server
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
